name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust this as necessary

      - name: Install Dependencies
        run: npm install

      - name: Inject Environment Variables
        run: |
          echo "REACT_APP_GENIUS_API_TOKEN=${{ secrets.REACT_APP_GENIUS_API_TOKEN }}" >> $GITHUB_ENV
          echo "REACT_APP_AZURE_SENTIMENT_ENDPOINT=${{ secrets.REACT_APP_AZURE_SENTIMENT_ENDPOINT }}" >> $GITHUB_ENV
          echo "REACT_APP_AZURE_SENTIMENT_ENDPOINT_KEY=${{ secrets.REACT_APP_AZURE_SENTIMENT_ENDPOINT_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_SPOTIFY_CLIENT_ID=${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_SPOTIFY_REDIRECT_URI=${{ secrets.REACT_APP_SPOTIFY_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "REACT_APP_BYPASS_CORS=${{ secrets.REACT_APP_BYPASS_CORS }}" >> $GITHUB_ENV

      - name: Build project
        run: npm run build
        env:
          REACT_APP_GENIUS_API_TOKEN: ${{ secrets.REACT_APP_GENIUS_API_TOKEN }}
          REACT_APP_AZURE_SENTIMENT_ENDPOINT: ${{ secrets.REACT_APP_AZURE_SENTIMENT_ENDPOINT }}
          REACT_APP_AZURE_SENTIMENT_ENDPOINT_KEY: ${{ secrets.REACT_APP_AZURE_SENTIMENT_ENDPOINT_KEY }}
          REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
          REACT_APP_SPOTIFY_REDIRECT_URI: ${{ secrets.REACT_APP_SPOTIFY_REDIRECT_URI }}
          REACT_APP_BYPASS_CORS: ${{ secrets.REACT_APP_BYPASS_CORS }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # Branch to deploy to
          folder: build  # Folder to deploy
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is correct
